# Generated by Django 5.2.4 on 2025-07-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifrost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('framework', models.CharField(choices=[('plain', 'Plain HTML/CSS/JS')], max_length=50)),
                ('output_type', models.CharField(choices=[('full', 'Full Page'), ('component', 'Components Only')], max_length=50)),
                ('css_type', models.CharField(choices=[('regular', 'Regular CSS'), ('tailwind', 'Tailwind CSS')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_code', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
