# Generated by Django 5.2.4 on 2025-07-27 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifrost', '0004_uploadhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadhistory',
            name='conversion_option',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='uploaded_image',
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='css_style',
            field=models.CharField(choices=[('inline', 'Inline Styles'), ('external', 'External CSS'), ('css_modules', 'CSS Modules'), ('styled_components', 'Styled Components')], default='external', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='framework_type',
            field=models.CharField(choices=[('vanilla', 'plain HTML/CSS/JS'), ('bootstrap', 'Bootstrap'), ('tailwind', 'Tailwind CSS'), ('foundation', 'Foundation')], default='vanilla', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='cloud_image_url',
            field=models.URLField(default='https://via.placeholder.com/300x200.png?text=No+Image', max_length=500),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='css_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='html_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='js_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
