# Generated by Django 5.2.4 on 2025-07-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifrost', '0005_remove_uploadhistory_conversion_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadhistory',
            name='cloud_image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='css_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='css_style',
            field=models.CharField(choices=[('inline', 'Inline Styles'), ('external', 'External CSS'), ('css_modules', 'CSS Modules')], default='external', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='framework_type',
            field=models.CharField(choices=[('plain', 'Plain HTML/CSS/JS'), ('bootstrap', 'Bootstrap'), ('tailwind', 'Tailwind CSS')], default='plain', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='html_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='js_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='ocr_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
